-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, 
	   ROUND(SUM(purchase_amount),0) as total_revenue
FROM   customer
GROUP BY gender
ORDER BY total_revenue DESC;       


-- Q2. Which customers used a discount but still spent more than the average purchase amount?  

SELECT customer_id, 
	   purchase_amount
FROM   customer 
WHERE discount_applied = "Yes" AND 
						 purchase_amount >=
                         (SELECT AVG(purchase_amount) 
                         FROM customer)
                         ORDER BY purchase_amount DESC;
                         
       